language: generic
os:
  - linux
dist: trusty
sudo: false
env:
  global:
    - DEVKITARM=$HOME/devkitARM
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
cache:
  apt: true
install:
  - cd $HOME
  - travis_retry wget http://download.sourceforge.net/devkitpro/devkitARM_r46-x86_64-linux.tar.bz2
  - tar xf devkitARM*.tar.bz2
  - travis_retry git clone https://github.com/YamaArashi/agbcc.git
  - cd agbcc && ./build.sh && ./install.sh $TRAVIS_BUILD_DIR
script:
  - cd $TRAVIS_BUILD_DIR
  - ./whitespace.sh
  - ./build_tools.sh
  - make -j2 compare_ruby_de
